export const RealtimeConfig = Object.freeze({
    MAX_CONNECTIONS: 100,
    MAX_PAYLOAD: 256,
    BROADCAST_INTERVAL_MS: 66, // ~15Hz
    PING_INTERVAL_MS: 30000,
    RATE_LIMIT_MAX: 30,
    RATE_LIMIT_WINDOW_MS: 1000,
    STALE_TTL_MOBILE_MS: 2000,
    STALE_TTL_DESKTOP_MS: 5000,
    OLD_LINEAGE_GRACE_MS: 1200,
    MAX_CURSORS_PER_CLIENT: 8,
    CLIENT_ID_MIN_LEN: 12,
    CLIENT_ID_MAX_LEN: 64,
    SESSION_ID_MIN_LEN: 12,
    SESSION_ID_MAX_LEN: 64,
    WS_PATH: '/ws',
    DEBUG_WS: process.env.WS_DEBUG === '1',
})

